### PR TITLE
Run `npm update` to fix broken truffle box

### PR DESCRIPTION
**Pull request by chuckbergeron**
Fixes issues #35 and #26 and #24.

I ran `npm update` (mentioned in #24) which updates `drizzle`, `drizzle-react`, `drizzle-react-components` and `react-router` which allows the truffle box's `npm start` command to run & launch the server without errors.

Note: You will need to re-compile and re-migrate the contracts if you had previously compiled / migrated against the old node_modules versions.

### CODE REVIEW

**Comment by pcowgill** [comment]
@DiscRiskandBisque @pemulis Is this good to merge?

**Comment by ecouffes** [comment]
For me, not worked with the drizzle minor version 1.2.x ;

there are two errors:
```
webpackHotDevClient.js:231 
Error in ./~/drizzle/drizzle.js
Module not found: 'deepmerge' in /path/to/drizzle/node_modules/drizzle
@ ./~/drizzle/drizzle.js 3:102-122
```

```
webpackHotDevClient.js:231 
Error in ./~/drizzle/drizzle.js
Module not found: 'is-plain-object' in /path/to/drizzle/node_modules/drizzle
@ ./~/drizzle/drizzle.js 3:124-150
```

I've fiexed the package.json where I change 
```
"drizzle": "^1.1.5",
```
into
```
"drizzle": "1.1.5",
```
in order to prevent npm from minor-updating the drizzle module over 1.2.x .

**Comment by pcowgill** [comment]
I also had the same issue. I ended up manually installing `deepmerge` and `is-plain-object`, and that also fixed it, but I like @ecouffes 's solution better.

**Comment by pcowgill** [comment]
@chuckbergeron Should we incorporate @ecouffes 's change into this PR before merging?

**Comment by barabis** [comment]
It seems to me that Drizzle 1.2.x is broken as generateContractsInitialState is undefined when I consoled it out.

I did however manage to get it working with version 1.1.5 as per ecouffes' advice

**Comment by mnaamani** [comment]
The root cause is bug in drizzle, see #24 for details. Once that fix is merged (https://github.com/trufflesuite/drizzle/pull/95) and a new version of drizzle is published, we can update drizzle-box to use it.

cc: @DiscRiskandBisque

**Comment by adrianmcli** [comment]
@chuckbergeron Hey thanks for submitting this PR. This project definitely needs a lot more attention (and I hope to bring it!).

A few things have changed since this PR was submitted. `drizzle@v1.2.2` has been released and I think it should work if you bump it up to that version. But while we're editing the `package.json`, why not also bring the Drizzle dependencies out of `devDependencies` and put it in `dependencies` where they belong.

I'm working on a new Truffle box from the ground up, but in the mean time we can hopefully fix this box so people can use what we already have. Thanks!

**Comment by chuckbergeron** [comment]
Sure @adrianmcli ! Here's the new (now working) PR: https://github.com/truffle-box/drizzle-box/pull/49

**Pull request closed without merging**
